<a href="https://colab.research.google.com/github/amitha2k/numpy_exercises/blob/main/12_Sorting_searching_and_counting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Soring, searching, and counting

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.21.6'

In [ ]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [ ]:
x = np.array([[1,4],[3,1]])
np.ndarray.sort(x)

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [ ]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
np.lexsort((surnames, first_names))

array([1, 2, 0])

Q3. Get the indices that would sort x along the second axis.

In [ ]:
x = np.array([[1,4],[3,1]])
np.argsort(x)

array([[0, 1],
       [1, 0]])

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [ ]:
x = np.random.permutation(10)
x = np.partition(x, 5)
print ("x =", x)


x = [0 1 2 4 3 5 8 6 9 7]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [ ]:
x = np.random.permutation(10)
print (x)
x = np.argpartition(x,3)
print ("x =", x)


[9 5 0 1 6 3 2 7 4 8]
x = [2 3 6 5 8 1 4 7 9 0]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.permutation(10).reshape(2, 5)
print ("x =", x)
print ("maximum values=", np.max(x,axis=1))
print ("max indices=", np.argmax(x,axis=1))
print ("minimum values=", np.min(x,axis=1))
print("min indices=", np.argmin(x,axis=1))
'''
x = [[0 5 9 8 2]
 [3 7 4 1 6]]
maximum values = [9 7]
max indices = [2 1]
minimum values = [0 1]
min indices = [0 3]
'''


x = [[5 9 0 3 6]
 [2 7 4 1 8]]
maximum values= [9 8]
max indices= [1 4]
minimum values= [0 1]
min indices= [2 3]


'\nx = [[0 5 9 8 2]\n [3 7 4 1 6]]\nmaximum values = [9 7]\nmax indices = [2 1]\nminimum values = [0 1]\nmin indices = [0 3]\n'

Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [ ]:
x = np.array([[np.nan, 4], [3, 2]])
'''
maximum values ignoring NaNs = [ 4.  3.]
max indices = [1 0]
minimum values ignoring NaNs = [ 4.  2.]
min indices = [1 1]
'''
print("max vals ignoring nans=", np.nanmax(x,axis=1))
print("max indices=",np.nanargmax(x,axis=1))
print("min vals ignoring nans=", np.nanmin(x,axis=1))
print("min indices=",np.nanargmin(x,axis=1))

max vals ignoring nans= [4. 3.]
max indices= [1 0]
min vals ignoring nans= [4. 2.]
min indices= [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [ ]:
x = np.array([[1, 2, 3], [1, 3, 5]])
'''
Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))
'''
print("Values bigger than=", x[x>2])
print("Their indices are", np.nonzero(x>2))

Values bigger than= [3 3 5]
Their indices are (array([0, 1, 1]), array([2, 1, 2]))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [ ]:
x = np.array([[1, 2, 3], [1, 3, 5]])
np.flatnonzero(x>2)


array([2, 4, 5])

Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [ ]:
x = np.arange(-5, 4).reshape(3, 3)
np.where(x>0,x,0)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [ ]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]
np.searchsorted(x,y)
'''
array([0, 2, 1, 3], dtype=int64)

'''


'\narray([0, 2, 1, 3], dtype=int64)\n\n'

## Counting

Q12. Get the number of nonzero elements in x.

In [ ]:
x = [[0,1,7,0,0],[3,0,0,2,19]]


5


In [ ]:
np.count_nonzero(x)

5