# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

## Matrix and vector products

Q1. Predict the results of the following code.

In [10]:
x = [1,2]
y = [[4, 1], [2, 2]]
#print np.dot(x, y)     array([8, 5])
#print np.dot(y, x)     array([6, 6])
#print np.matmul(x, y)  array([8, 5])
#print np.inner(x, y)   array([6, 6])
#print np.inner(y, x)   array([6, 6])

Q2. Predict the results of the following code.

In [13]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
#print np.dot(y, x)       array([[4,1],[2,2],[1,1]])
#print np.matmul(y, x)    array([[4,1],[2,2],[1,1]])
np.matmul(y,x)

array([[4, 1],
       [2, 2],
       [1, 1]])

Q3. Predict the results of the following code.

In [19]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
#print np.vdot(x, y)                        30
#print np.vdot(y, x)                        30
#print np.dot(x.flatten(), y.flatten())     30
#print np.inner(x.flatten(), y.flatten())   30
#print (x*y).sum()                          30

30

Q4. Predict the results of the following code.

In [ ]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
#print np.inner(x, y)   array(['a','bb'])
#print np.inner(y, x)   array(['a','bb'])
#print np.outer(x, y)   array([['a','aa'],['b','bb']])
#print np.outer(y, x)   array([['a','b'],['aa','bb']])

## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [ ]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)


[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Q6. Compute the qr factorization of x and verify it.

In [ ]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)


q=
[[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [ ]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)


U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
[ 3.          2.23606801  2.          0.        ] 
V=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [23]:
x = np.diag((1, 2, 3))
eigenvals, eigenvecs = np.linalg.eig(x)



Q9. Predict the results of the following code.

In [28]:
#print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)   True
np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)

True

## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [5]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x, 'fro'))
np.linalg.cond(x)
'''
16.8819430161
4.56177073661e+17
'''

16.881943016134134


'\n16.8819430161\n4.56177073661e+17\n'

Q11. Calculate the determinant of x.

In [34]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

Q12. Calculate the rank of x.

In [30]:
x = np.eye(4)
np.linalg.matrix_rank(x)

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [35]:
x = np.arange(1, 5).reshape((2, 2))
'''
-1.0 0.69314718056
'''
np.sign(np.linalg.det(x)), np.log(np.linalg.det(x))



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """


(-1.0, nan)

Q14. Return the sum along the diagonal of x.

In [36]:
x = np.eye(4)
np.trace(x)


4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [37]:
x = np.array([[1., 2.], [3., 4.]])

np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])